apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spawner
  annotations:
    homeroom/title: "Kubernetes Fundamentals"
    homeroom/description: "A workshop introducing developers to Kubernetes"
